<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>State Diagram for Regular Expression 1</title>
  <style>
    svg {
      margin: 20px;
      border: 1px solid #ccc;
    }
    circle {
      fill: #f9f9f9;
      stroke: #000;
      stroke-width: 2;
    }
    text {
      font-family: Arial, sans-serif;
      font-size: 14px;
    }
    path {
      fill: none;
      stroke: #000;
      stroke-width: 2;
      marker-end: url(#arrowhead);
    }
  </style>
</head>
<body>
  <h1>State Diagram for Regular Expression 1</h1>
  <svg width="600" height="300">
    <!-- Arrowhead definition -->
    <defs>
      <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
        <polygon points="0 0, 10 3.5, 0 7" fill="#000"></polygon>
      </marker>
    </defs>

    <!-- States -->
    <circle cx="50" cy="150" r="25"></circle>
    <text x="42" y="155">q0</text>
    <circle cx="200" cy="150" r="25"></circle>
    <text x="192" y="155">q1</text>
    <circle cx="350" cy="150" r="25"></circle>
    <text x="342" y="155">q2</text>
    <circle cx="500" cy="150" r="25" stroke="green" stroke-width="3"></circle>
    <text x="492" y="155">qf</text>

    <!-- Transitions -->
    <path d="M75,150 L175,150" marker-end="url(#arrowhead)"></path>
    <text x="120" y="140">a</text>

    <path d="M225,150 L325,150" marker-end="url(#arrowhead)"></path>
    <text x="270" y="140">a</text>

    <path d="M375,150 L475,150" marker-end="url(#arrowhead)"></path>
    <text x="420" y="140">a, b</text>

    <!-- Loop -->
    <path d="M200,125 C180,70 220,70 200,125" marker-end="url(#arrowhead)"></path>
    <text x="185" y="90">a</text>

    <path d="M350,125 C330,70 370,70 350,125" marker-end="url(#arrowhead)"></path>
    <text x="335" y="90">a, b</text>
  </svg>
</body>
</html>

